#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-quickstart - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- Openai_Responses (LLM)
- Cartesia (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

import os

from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.frames.frames import LLMRunFrame
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.worker import PipelineParams, PipelineWorker
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.runner.types import RunnerArguments
from pipecat.runner.utils import create_transport
from pipecat.services.cartesia.tts import CartesiaTTSService
from pipecat.services.deepgram.stt import DeepgramSTTService
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.transports.daily.transport import DailyParams
from pipecat.workers.runner import WorkerRunner
from pipecat.services.openai.llm import OpenAILLMService

# --- NEW imports needed for function calling ---
from pipecat.adapters.schemas.function_schema import FunctionSchema
from pipecat.adapters.schemas.tools_schema import ToolsSchema
from pipecat.services.llm_service import FunctionCallParams
from pipecat.services.deepgram.tts import DeepgramTTSService
from pipecat.services.sarvam.stt import SarvamSTTService
from pipecat.services.sarvam.tts import SarvamTTSService


load_dotenv(override=True)
import aiohttp

from rag_processor import RAGProcessor

N8N_WEBHOOK_URL = "http://localhost:5678/webhook/create-event"

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
VECTOR_DB_PATH = os.path.normpath(
    os.path.join(BASE_DIR, "..", "..", "vector_db")
)


# --- NEW: function handler moved to module level, new signature ---
async def book_appointment_tool(params: FunctionCallParams):
    """Hits the local n8n container when the LLM triggers function calling."""
    arguments = params.arguments
    logger.info(f"LLM requested booking: {arguments}")

    payload = {
        "title": arguments.get("title", "Hospital Appointment"),
        "start": arguments.get("start"),
        "end": arguments.get("end"),
    }

    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(
                N8N_WEBHOOK_URL, json=payload, timeout=aiohttp.ClientTimeout(total=10)
            ) as response:
                if response.status in (200, 201):
                    logger.info("Successfully pushed metadata to n8n.")
                    await params.result_callback(
                        "Appointment successfully registered in the system calendar."
                    )
                else:
                    await params.result_callback(
                        "The booking system is busy. Please try again."
                    )
    except Exception as e:
        logger.error(f"Failed to communicate with n8n: {e}")
        await params.result_callback(
            "Internal connection error. Could not write to the calendar."
        )


async def run_bot(transport: BaseTransport, runner_args: RunnerArguments) -> None:
    """Run the voice bot for this session.

    Args:
        transport: The transport for this session, built by ``create_transport``
            (or by hand for the dial-out/SIP production flows).
        runner_args: Runner session arguments. Carries the request ``body``
            (e.g. dial-out settings, SIP call details) and ``session_id``; the
            standard web/telephony pipelines don't need it.
    """
    logger.info("Starting bot")

    # Speech-to-Text service
    stt = SarvamSTTService(
    api_key=os.getenv("SARVAM_API_KEY"),
    settings=SarvamSTTService.Settings(model="saaras:v3", mode="translate"),
    )

    # Text-to-Speech service
    # tts = DeepgramTTSService(
    #     api_key=os.getenv("DEEPGRAM_API_KEY"),
    #     voice=os.getenv("DEEPGRAM_VOICE", "aura-asteria-en"),
    # )
    tts = SarvamTTSService(
    api_key=os.getenv("SARVAM_API_KEY"),
    settings=SarvamTTSService.Settings(language="od-IN"),
    )

    # --- NEW: FunctionSchema + ToolsSchema instead of raw OpenAI dict ---
    appointment_function = FunctionSchema(
        name="book_appointment",
        description="Call this when the user confirms a specific purpose, date, and time for an appointment. or you can suggest 2 options of time and date around the current data and time today is 12/07/2026 and give the perpose acouding to user needs which doctor.",
        properties={
            "title": {
                "type": "string",
                "description": "Appointment reason, e.g., 'Checkup with Dr. Smith'",
            },
            "start": {
                "type": "string",
                "description": "ISO 8601 start time, e.g., '2026-07-15T10:00:00Z'",
            },
            "end": {
                "type": "string",
                "description": "ISO 8601 end time, e.g., '2026-07-15T11:00:00Z'",
            },
        },
        required=["title", "start", "end"],
    )
    tools = ToolsSchema(standard_tools=[appointment_function])

    # LLM service — NOTE: no tools= here anymore
    llm = OpenAILLMService(
        api_key=os.getenv("OPENAI_API_KEY"),
        base_url=os.getenv("OPENAI_BASE_URL", "http://localhost:11434/v1"),
        settings=OpenAILLMService.Settings(
            model=os.getenv("OPENAI_MODEL", "llama3.1:latest"),
        ),
    )

    # --- NEW: register_function instead of register_tool_handler ---
    llm.register_function("book_appointment", book_appointment_tool)

    messages = [
        {
            "role": "system",
            "content": (
                "You are a helpful assistant at a private hospital who guides customers according to their needs. "
                "Provide information about doctors using your context. When a customer explicitly confirms they want to book an appointment, "
                "gather the purpose, start time, and end time, then immediately trigger the 'book_appointment' tool. "
                "After a successful booking, ask for feedback and thank them."
            ),
        },
    ]

    # --- NEW: tools passed into the context, not the llm ---
    context = LLMContext(messages, tools=tools)
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(vad_analyzer=SileroVADAnalyzer()),
    )

    rag = RAGProcessor(context=context, db_path=VECTOR_DB_PATH, top_k=2)

    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            rag,                 # <-- retrieves + injects context here
            user_aggregator,
            llm,
            tts,
            transport.output(),
            assistant_aggregator,
        ]
    )

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[],
    )

    @worker.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        # Kick off the conversation
        context.add_message(
            {"role": "developer", "content": "Start by concisely introducing yourself."}
        )
        await worker.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await worker.cancel()

    runner = WorkerRunner(handle_sigint=False)

    await runner.add_workers(worker)
    await runner.run()


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport_params = {
        "daily": lambda: DailyParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
        "webrtc": lambda: TransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
    }

    transport = await create_transport(runner_args, transport_params)

    await run_bot(transport, runner_args)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()